# Generated by Django 4.2.7 on 2023-12-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=500, upload_to='output/vid/'),
        ),
    ]
