# Generated by Django 4.2.7 on 2023-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default=models.FileField(upload_to='videos/'), max_length=100),
        ),
    ]
